[package]
name = "w4-padding_oracle_attack"
version = "0.1.0"
authors = ["mikong <4162+mikong@users.noreply.github.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.11"
hex-literal = "0.1.3"
hex = "0.3.2"
