[package]
name = "w2-aes"
version = "0.1.0"
authors = ["mikong <4162+mikong@users.noreply.github.com>"]
edition = "2018"

[dependencies]
hex-literal = "0.1.3"
aes-soft = "0.3.3"
block-padding = "0.1.3"
rand_os = "0.1.3"
