[package]
name = "w6-rsa_problem"
version = "0.1.0"
authors = ["mikong <4162+mikong@users.noreply.github.com>"]
edition = "2018"

[profile.dev]
opt-level = 3

[dependencies]
num-bigint = "0.2"
num-traits = "0.2"
